version: "3.7"
services:
  webapp:
    build:
      context: ./docker-app
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
  serverapp:
    build:
      context: ./Api
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"